 Name:ABBO FULUMERA
REG NO:2022/DCSE/013/SS
TEST: 1
 DATE:29-07-2022
 SECTION 1

In [ ]:
# importing labraries

In [28]:
import numpy as np

In [29]:
import matplotlib.pyplot as plt

QN 1
C

QN 2
D

QN 3


QN 4
A

QN 5
C

QN 6
B

QN 7
C

QN 8
D Because it is indepedent.

 QN 9
 a
D

QN 10
a
B

QN 10
B
4

In [ ]:
SECTION 2

In [2]:
import numpy as np

In [ ]:
import matplotlib.pyplot as plt

In [21]:
import math

In [22]:
#QN 5
1
x = np.array([[25, 2], [5, 26], [3, 7]])
print(x.shape)

(3, 2)


In [6]:
#QN 5 Transponsing matrix using list comprehension
2
x = np.array([[25, 2], [5, 26], [3, 7]])
result = [[X[j][i] for j in range(len(X))] for i in range(len(X[0]))]

for b in result:
   print(b)

[25, 5, 3]
[2, 26, 7]


In [7]:
#QN 5 multiplication of matrix by a scaler
3
x = np.array([[25, 2], [5, 26], [3, 7]])
s=3*np.array([[25, 2], [5, 26], [3, 7]])
print(s)

[[75  6]
 [15 78]
 [ 9 21]]


In [14]:
#QN5  multiplication of matrices X and A
4
A = ([[3, 4], [5, 6], [7, 8]])
result = [[A[j][i] for j in range(len(A))] for i in range(len(A[0]))]
for y in result:
 print(y)
# results of the transponse of matrixes x and A

[3, 5, 7]
[4, 6, 8]


Matix x=b
      A=y

In [16]:
 multiplication of 2x2 matrixes which is the results of the transponse of matrixes x and A
b=np.array([[25, 5, 3],
[2, 26, 7]])
y=np.array([[3, 5, 7],
[4, 6, 8]])
print(b*y)

[[ 75  25  21]
 [  8 156  56]]


In [23]:
# QN 5
5 #Getting inverse of  the result of multiplication of matrices
arr = np.array([[75, 25, 21], [8, 156, 56]])
inverse_array = np.linalg.inv(arr)
print("Inverse array is ")
print(inverse_array)
print(arr)

LinAlgError: Last 2 dimensions of the array must be square

QN 6

In [27]:
k=np.array([[1, 0.2, 0.5],[0.2, 1, 0.8],[0.5, 0.8, 1]])
result = [[k[j][i] for j in range(len(k))] for i in range(len(k[0]))]# getting the transponse first
for n in result:
   print(n)
#getting the inversion of the transponse
trans=([[1.0, 0.2, 0.5],
[0.2, 1.0, 0.8],
[0.5, 0.8, 1.0]])
inverse_array = np.linalg.inv(trans)
print("Inverse array is ")
print(inverse_array)
print(trans)

[1.0, 0.2, 0.5]
[0.2, 1.0, 0.8]
[0.5, 0.8, 1.0]
Inverse array is 
[[ 1.56521739  0.86956522 -1.47826087]
 [ 0.86956522  3.26086957 -3.04347826]
 [-1.47826087 -3.04347826  4.17391304]]
[[1.0, 0.2, 0.5], [0.2, 1.0, 0.8], [0.5, 0.8, 1.0]]
